### ISSUE TITLE
OAuth token

### ISSUE THREAD

**Issue by Axis963** [MrSprigster/Twitch.tv-on-XBMC#601]
Today followings just disappear :/ When i try to create new OAuth token its not working. I subscribe Amazon Prime today and I linked it with Twitch, maybe this cause problem?

![obraz](https://user-images.githubusercontent.com/34260785/137024368-1cd15d10-a665-4412-a3d2-b85df0fbf85f.png)

**Comment by neo-neo1** [comment]
This is not related to this Kodi Addon. That is from another website.
