### ISSUE TITLE
No Videos or Streams will Play

### ISSUE THREAD

**Issue by ghost** [MrSprigster/Twitch.tv-on-XBMC#602]
* Add-on Version: 2.5.11+matrix.1
* Kodi Version: 19.1
* Kodi GUI Language: American English
* Operating System: LibreELEC 10.0.0
* Operating System Language: American English

------

### Expected Behavior

Stream or video is selected, and it plays normally.

------

### Current Behavior

Stream or video is selected, error notification saying it failed to play, nothing plays, nothing in debug log.

------

### Steps to Reproduce

1. Select any video or stream on the Twitch addon
2. Error pop-up
3. Nothing plays

------

### Log

There is nothing in my event log, despite the notification saying I should check the log for more information.

------

### Additional Information

It worked until the other day. Logged in, logged out, no difference. Nothing will play. I reinstalled the addon, and I could play streams while logged out, but as soon as I logged back in, nothing would play, even if I logged back out.

**Comment by anxdpanic** [comment]
Need a complete debug log. https://kodi.wiki/view/Log_file/Easy
