### ISSUE TITLE
[Feature Request] Hey there, I made some icons for twitch if you would like to use them. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [MrSprigster/Twitch.tv-on-XBMC#604]
### What Problem Does This Solve? 

Please provide a concise description of the problem this request solves.

My Concise Problem : It Solves the missing icon problem sense twitch does not have any icons.

------
### Suggest a Solution (optional)

Please provide a concise description of your suggested solution. If there are multiple solutions, describe them independently and optionally follow them with a comparison.

My Concise Solution: I don't have a solution but if you don't add these icons to twitch then i will use [Autowidget](https://github.com/drinfernoo/plugin.program.autowidget) and thats totally fine.

------
Hey there, i was bored and had nothing to do today so i made you some icons for twitch and i hope these will help you out. If there is an icon that you want me to change, i will change it for you and if you don't want to use these icons, that's totally fine. Hope you have a great day and hope these will help and thank you.

[Twitch Icons.zip](https://github.com/anxdpanic/plugin.video.twitch/files/7629444/Twitch.Icons.zip)
![image](https://user-images.githubusercontent.com/62456796/144142304-8ac71e4c-885b-45bd-905f-d6098113f421.png)

**Comment by Goldenfreddy0703** [comment]
Hey i just got done adding them to my build so here are some screenshots i took of how they would look if you are ever interested on adding these icons. 

![image](https://user-images.githubusercontent.com/62456796/144146572-7cb958f9-7bbd-4f65-8d07-c3fa6d2c163e.png)
![image](https://user-images.githubusercontent.com/62456796/144146628-6efb86d6-df68-4702-b639-78c8ee6e86b5.png)
![image](https://user-images.githubusercontent.com/62456796/144146662-c0acdea2-6186-475b-8bb1-77224db8744b.png)
![image](https://user-images.githubusercontent.com/62456796/144146690-03071aa6-9cd0-4d31-97e2-c4e3b3b12361.png)
![image](https://user-images.githubusercontent.com/62456796/144365214-022410b8-dd8a-4783-b9d9-17717efa065a.png)

**Comment by neo-neo1** [comment]
Thanks for sharing this. Unfortunately it seems the lone dev here has been missing for many months (if not a year) now :/
Might be time for an able bodied person to consider a fork of this abandoned project?

**Comment by anxdpanic** [comment]
I am still here, and should have time again soon. If someone sets this up as a PR, that would help as well.

**Comment by anxdpanic** [comment]
nm im blind too! :)
