### ISSUE TITLE
Ads still showing when subscribed

### ISSUE THREAD

**Issue by clenz93** [MrSprigster/Twitch.tv-on-XBMC#608]
### Context

Please provide any relevant information about your setup

* Add-on Version: 2.5.11
* Kodi Version: 18.7
* Kodi GUI Language: English
* Operating System: Raspbian GNU/Linux 10
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.

While watching a streamer I am subscribed to, ads should be skipped

------

### Current Behavior

What is the current behavior?

Ads are not skipped, instead a "Commercial in progress" screen is shown

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Watch streamer to whom you are subscribed
2. Wait for streamer to run ads
3. Commercials may also run when beginning stream as well.

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

To be added later.

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by neo-neo1** [comment]
[Covered in Wiki](https://github.com/anxdpanic/plugin.video.twitch/wiki/Subscription-and-Turbo-benefits) Not a bug.

Also previously [asked and asnwered](https://github.com/anxdpanic/plugin.video.twitch/issues/581).

Hope this helps. May the search be with you, next time.

**Comment by greatquux** [comment]
I can confirm that after entering my OAuth token following instructions in the wiki, the addin is not showing ads for channels I am subscribed to.  Which is great since the mid-roll ads were causing an OOPS in the RPi 400 kernel! (Not your fault of course, some bug in V4L).  Thanks for looking into it.
