### ISSUE TITLE
404 API Twitch error

### ISSUE THREAD

**Issue by Lookens** [MrSprigster/Twitch.tv-on-XBMC#616]
Getting errors trying to access the addon today. Havent changed anything with my setup. Error in Kodi says Failed to Connect to Twitch API. Nothing loads. Logs attached below.

Please provide any relevant information about your setup

Add-on Version: 2.5.1.2
Kodi Version: 19.1
Kodi GUI Language: English
Operating System: OSMC 2020.10-1
Operating System Language: English
Expected Behavior
See streams

Current Behavior
Nothing loads at all

Steps to Reproduce
Please provide detailed steps for reproducing the issue.

Open Addon

**Comment by Lookens** [comment]
I saw this post : https://github.com/anxdpanic/plugin.video.twitch/issues/537 and nothing works

**Comment by anxdpanic** [comment]
https://blog.twitch.tv/en/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/ see the section on downtime.

```
v5 shutdown timeline
Given the number of v5 migrations, we wanted to ensure that you have sufficient time to update your applications and that we are reaching developers as soon as possible. A phased shutdown of v5 will begin in February 2022. Here are the shutdown windows:

February 7, 2022 – 1-hour shutdown starting at 11:00am PDT
February 9, 2022 – 2-hour shutdown starting at 11:00am PDT
February 14, 2022 – 4-hour shutdown starting at 11:00am PDT
February 16, 2022 – 6-hour shutdown starting at 11:00am PDT
February 22, 2022 – 24-hour shutdown starting at 11:00am PDT
February 28, 2022 – v5 permanent shutdown
```

**Comment by Lookens** [comment]
Oh ok thanks 👍
