### ISSUE TITLE
Fanart not showing in "Following live channels" stream info in alpha2

### ISSUE THREAD

**Issue by jonisb** [MrSprigster/Twitch.tv-on-XBMC#627]
### Context

Please provide any relevant information about your setup

* Add-on Version: v2.6.0~alpha2
* Kodi Version: 18.8.0
* Kodi GUI Language: English
* Operating System: Windows 10
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.

Fanart showing for channels.

------

### Current Behavior

What is the current behavior?

Fanart is blank for "Live channels" and "Following live channels"

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
In Twitch plugin choose "Following live channels"
2. 
Pick a live stream press i (info)
3. 
Press the "Show fanart" button
4.
Get blank screen

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://paste.kodi.tv/fuzitivena.kodi

------

### Additional Information

Please provide any additional information that may be helpful.
This is related to my comment about missing thumbnail in widgets here: https://github.com/anxdpanic/plugin.video.twitch/issues/615#issuecomment-1042464098

------

**Comment by anxdpanic** [comment]
the default fanart has been fixed in beta1
the api doesn't return any images besides the preview thumbnail now

**Comment by jonisb** [comment]
Hmm, so in beta1 I'm getting a generic twitch image, that is kinda useless anything stream/channel related would be more useful I think.
Now the VOD section also shows the same twitch image, in alpah2 I was getting a channel specific image so this seems like a regression.

**Comment by anxdpanic** [comment]
I don't know what stream specific image you'd be getting in the alpha...
```
                                                    {
                                                        "created_at": "2022-01-10T20:45:18Z",
                                                        "description": "",
                                                        "duration": "2h32m46s",
                                                        "id": "1259478057",
                                                        "language": "en",
                                                        "muted_segments": null,
                                                        "published_at": "2022-01-10T20:45:18Z",
                                                        "stream_id": "45099770173",
                                                        "thumbnail_url": "https://static-cdn.jtvnw.net/cf_vods/d1m7jfoe9zdc1j/5fa8ff26ecc41e3858a0_g4tv_45099770173_1641847509//thumb/thumb0-%{width}x%{height}.jpg",
                                                        "title": "We Found Our Ultimate Dream Daddy ft. Gina Darling [GinAppropriate Behavior]",
                                                        "type": "archive",
                                                        "url": "https://www.twitch.tv/videos/1259478057",
                                                        "user_id": "7633324",
                                                        "user_login": "g4tv",
                                                        "user_name": "G4TV",
                                                        "view_count": 13128,
                                                        "viewable": "public"
                                                    }
```

The request only returns the preview thumbnail, same with streams. I will look at adding additional api requests to these areas to pull the channels offline image (what it used to be)

**Comment by jonisb** [comment]
I might be going crazy as I'm sure I got an image in the VODs in alpha2 but I retried alpha2 and I get the same black image now, so sorry for the misinformation.

I would prefer the preview thumbnail as that's whats show in the widget my skin uses but the channels offline image would probably be preferable.

**Comment by anxdpanic** [comment]
heh, no worries at all 👍 

I added the offline images for videos and streams in beta2

**Comment by jonisb** [comment]
Thanks, beta2 shows usable thumbnails again.
