### ISSUE TITLE
Please use https for the dev repo

### ISSUE THREAD

**Issue by pitsi** [MrSprigster/Twitch.tv-on-XBMC#641]
### What Problem Does This Solve? 
Right now, the dev repo uses plain http as seen in its addon.xml
```
        <extension point="xbmc.addon.repository" name="Twitch Development Repository">
        <info compressed="false">http://panicked.xyz/repository/twitch/python2/addons.xml</info>
        <checksum>http://panicked.xyz/repository/twitch/python2/addons.xml.md5</checksum>
        <datadir zip="true">http://panicked.xyz/repository/twitch/python2/zips/</datadir>
        </extension>
```
which makes kodi issue this warning at every start
```
2022-02-23 12:19:23.463 T:140032606869632 WARNING: Repository add-on repository.twitch_development uses plain HTTP for add-on downloads in path http://panicked.xyz/repository/twitch/python2/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
```
I also think this is the reason kodi 19 does not automatically upgrade twitch to any new version on my end, as I describe here
https://forum.kodi.tv/showthread.php?tid=356449&pid=3087652#pid3087652

------

### Suggest a Solution (optional)

Just change those 3 lines that start with http to https. In a web browser that automatically upgrades http to https, the forementioned urls work with no issue, so they should work with kodi too.
Obviously, the forementioned issue and the solution apply to the python3 part of the repo, the one for kodi 19+.

------
p.s. Since you are the maintainer for youtube's testing repo, can you do the same for it too?

**Comment by anxdpanic** [comment]
I've updated and pushed the twitch, youtube, tubed and composite dev repos with the change to https.

**Comment by pitsi** [comment]
Aaand it does not solve the update issue I mentioned in twitch's thread on kodi forum.
I launched kodi twice, just in case, force-checked for updates 5+ times in total, but twitch is still on 2.6.0-beta5.

**Comment by pitsi** [comment]
@anxdpanic 
Can you please move the final versions of twitch and python-twitch to the development repo for python3? It has 2.6.0-beta6 and 2.0.21-alpha2 respectively now, but the python2 part of the repo has the final versions of them. Thank you in advance :)

**Comment by pitsi** [comment]
Thank you :)

**Comment by anxdpanic** [comment]
Thought I had already done that, I got it pushed before I called it a night. 👍
