### ISSUE TITLE
Change of the Login sub-menu

### ISSUE THREAD

**Issue by IronGibbet** [MrSprigster/Twitch.tv-on-XBMC#643]
### What Problem Does This Solve? 

From the GUI it was not completely clear to me where to enter my OAuth Token for the new API.
I didn't have a Twitch account before the API change so the topmost "OAuth Token" Textbox was always empty and I didn't even realize it was a textbox at all.

After generating the token I entered it at bottom because it was below the "Get OAuth Token" function and there already was another value (OAuth Client ID).

Eventually I figured it out by looking in the settings.xml

It would imho improve user experience and lower the the eifok rate.

------

### Suggest a Solution (optional)

Please consider changing the order to 
"Get OAuth Token" --> "(Enter) OAuth Token" --> "Revoke Token".
Maybe even put the "Private API Credentials" section in the Developer sub-menu or add a switch that displaying this section in the Login sub-menu can be enabled or disabled (default to disabled) if you as dev still want/need to have a quick access to it. 
From what I understand those keys shouldn't be altered by a "normal" user anyway.

------

Thank you for the great work.

**Comment by Twilicious** [comment]
+1 Just spent 30 minutes tearing my hair out because i thought you had to enter the key in both boxes.

Got it working now though. THANKS!

**Comment by parasyte** [comment]
See also #651

**Comment by anxdpanic** [comment]
Submitted a fix to resolve this to the official repository.
