### ISSUE TITLE
Keep getting "Commerical break in progress" screens even on channel I subscribe to

### ISSUE THREAD

**Issue by hiemsmutus** [MrSprigster/Twitch.tv-on-XBMC#650]
### Context
* Add-on Version: 2.6.0
* Kodi Version: 19.4
* Kodi GUI Language: English US
* Operating System: Fire OS 7.2.5.5 / Fire TV Home Version 6341067.1
* Operating System Language: English US

------

### Expected Behavior
This worked fine with Kodi 18, but now I get these endless "Commericial break in progress" screens.

------

### Current Behavior
Keep getting "Commerical break in progress" screens even on a channel I subscribe to. Logs are at https://paste.kodi.tv/enovamuzef.kodi. This happens on both a fire tv stick and a raspberry pi, both running Kodi 19.4. The logs are for the fire tv stick. Bug info is for the fire tv stick. Let me know if any other info is needed. 

------

### Steps to Reproduce
1. Install Kodi 19.4 on Fire TV Stick
2. Install Twitch add-on
3. View subscribed channel, see constant commercial break screens

------

### Log
https://paste.kodi.tv/enovamuzef.kodi

------

### Additional Information
N/A

------

**Comment by anxdpanic** [comment]
https://github.com/anxdpanic/plugin.video.twitch/wiki/Subscription-and-Turbo-benefits

**Comment by hiemsmutus** [comment]
Awesome, worked great. Thank you!

**Comment by parasyte** [comment]
> https://github.com/anxdpanic/plugin.video.twitch/wiki/Subscription-and-Turbo-benefits

I've been using my OAuth token for months (with a Turbo account) and I constantly get commercial interruptions when using this addon. I'm using `inputstream.adaptive` as suggested elsewhere, and I have reset the function cache as described on the wiki. Nothing gets rid of ads for me, even though all of my following channels and everything from my account is picked up by the addon.

Edit: Found the issue and created #651 to suggest improvements.
