### ISSUE TITLE
Poor user experience: Two separate OAuth Tokens

### ISSUE THREAD

**Issue by parasyte** [MrSprigster/Twitch.tv-on-XBMC#651]
### Context

Please provide any relevant information about your setup

* Add-on Version: All
* Kodi Version: All
* Kodi GUI Language: All
* Operating System: All
* Operating System Language: All

------

### Expected Behavior

The user experience for handling login credentials needs to be streamlined for usability and to avoid confusion. The technical limitations leading to the issue are understood, but there are multiple ways to improve the user experience. A particularly easy improvement would be updating the "generate OAuth Token page" to include the instructions for setting the Private API OAuth Token (and why it's different from the generated token). Even just linking to the wiki would be helpful.

Give the tokens different names in the settings UI. Calling them both "OAuth Token" is factually correct, but absurd. The separate "Private API Credentials" section header is not adequate for distinction.

Additionally, the OAuth Client ID should probably not be shown in the UI at all. Set it to the documented default value and allow it to be overridden in configuration files if necessary.

The UI should be just a button at the top called something like "Login" that gives you the popup for what is currently the "generate OAuth Token page". And the two input fields: one for the "Login credential" (the generated token) and one for the "OAuth Token" that you manually copy from a cookie in your browser. The login page can provide details as described above.

------

### Current Behavior

There is a confusing and annoying settings page with two different "OAuth Token" inputs which require two different sets of permissions. This is documented in [Subscription and Turbo benefits](https://github.com/anxdpanic/plugin.video.twitch/wiki/Subscription-and-Turbo-benefits). These tokens have very different uses, and it is easy to put the wrong token into the wrong input field and be presented with an error message about the OAuth Client ID or OAuth Token that does not make sense in context. This is likely a leading cause for so many issues in this repo regarding ads showing up with subscriptions and Turbo.

Having two different wiki pages for seemingly the same purpose also does not help.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open the Settings UI
2. See two different fields to input "OAuth Token"
3. Search the internet and GitHub issues to find out what you're expected to do.
4. Read the docs and input the token into the wrong field anyway because the whole thing is overly confusing.

**Comment by anxdpanic** [comment]
Submitted a fix to resolve this to the official repository.

I can't do anything about the multi token, that's how it is. But it should now be less confusing.
