### ISSUE TITLE
Twitch plugin stopped working

### ISSUE THREAD

**Issue by lockie** [MrSprigster/Twitch.tv-on-XBMC#666]
### Context

The addon worked for me for some time, then a couple of days ago it stopped: it gets the video list, but when I click on the video, it shows "Attempting to reconnect" dialog indefinitely.

* Add-on Version: 2.6.2
* Kodi Version: 19.4
* Kodi GUI Language: English
* Operating System: Raspberry Pi OS
* Operating System Language: English

------

### Expected Behavior

Live twitch stream is played when I click on it.

------

### Current Behavior

When I click on a video,  "Attempting to reconnect, attempt # 1" dialog is being shown over and over again.

------

### Steps to Reproduce

1. Click on a plugin from the "Add-ons".
2. Click "Following".
3. Click "Live channels".
4. Click on any livestream.

------

### Log

https://paste.kodi.tv/naqolivaxi

------

### Additional Information

Seems like the relevant piece of Kodi log just says that it got EOF reading from demuxer.

------

**Comment by lockie** [comment]
*crickets chirp*

**Comment by anxdpanic** [comment]
sorry, the log is expired now. re-open with a new log. not sure there is anything add-on side that could be done though.
