### ISSUE TITLE
Please make the dev repo compatible for kodi 20

### ISSUE THREAD

**Issue by pitsi** [MrSprigster/Twitch.tv-on-XBMC#668]
### What Problem Does This Solve? 
Starting with kodi 20, repos must have a specific structure in their addon.xml file as described here.
https://kodi.wiki/view/Add-on_repositories#Repository_Add-on

Currently, the dev repo does not have such a structure
```
        <extension point="xbmc.addon.repository" name="Twitch Development Repository">
        <info compressed="false">https://download.osmc.tv/dev/anxdpanic/kodi/twitch/python3/addons.xml</info>
        <checksum>https://download.osmc.tv/dev/anxdpanic/kodi/twitch/python3/addons.xml.md5</checksum>
        <datadir zip="true">https://download.osmc.tv/dev/anxdpanic/kodi/twitch/python3/zips/</datadir>
        </extension>
```
which makes kodi pop up this message in its log
```
2023-01-30 07:12:23.593 T:1375    error <general>: Repository add-on repository.twitch_development uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2023-01-30 07:12:23.593 T:1375    error <general>: Repository add-on repository.twitch_development does not have any directory and won't be able to update/serve addons! Please fix the addon.xml definition
```
and a "could not connect to repository" messege once someone tries to install something from it (settings > addons > install from repository > twitch development repository).

------

### Suggest a Solution (optional)

Adding the `<dir>` tags in the right places as seen here makes the repo work again
```
        <extension point="xbmc.addon.repository" name="Twitch Development Repository">
        <dir>
        <info compressed="false">https://download.osmc.tv/dev/anxdpanic/kodi/twitch/python3/addons.xml</info>
        <checksum>https://download.osmc.tv/dev/anxdpanic/kodi/twitch/python3/addons.xml.md5</checksum>
        <datadir zip="true">https://download.osmc.tv/dev/anxdpanic/kodi/twitch/python3/zips/</datadir>
        </dir>
        </extension>
```
The same applies to yt_testing repo and probably all your other repos, so please fix them as well.
The new problem is that... if the repo does not work the way kodi 20 wants it to, it can not update itself to the new version that will contain the fix.

**Comment by anxdpanic** [comment]
Thanks for the heads up, ill have new repository links soon

**Comment by pitsi** [comment]
I just noticed that the dev repo (and yt_testing) has been updated to a kodi 20 compatible version... on kodi 18.
Unfortunately, I no longer have access to any kodi 20 installations so as to check, but the change is there even for the python2 version of the repo.

**Comment by anxdpanic** [comment]
I've updated the mirrors, will take a while to propagate.
https://download.osmc.tv/dev/anxdpanic/repositories/

The change makes the repositories compatible with kodi 18 and matrix+ so that should be fine !
