### ISSUE TITLE
Commercial break appear despite being a subscriber to the channel

### ISSUE THREAD

**Issue by ffais** [MrSprigster/Twitch.tv-on-XBMC#670]
### Context

Please provide any relevant information about your setup

* Add-on Version: 2.6.2+matrix.1
* Kodi Version: 20.0.0
* Kodi GUI Language: Italian
* Operating System: Android TV 9.0.0 (MiBox S)
* Operating System Language: Italian

------

### Expected Behavior

Skip all the commercial breaks when subscribed to a channel.

------

### Current Behavior

I keep seeing 'Commercial Break in progress' even if I'm subscribed to the channel.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Insert the login token in Settings
2. Subscribe to a channel
3. Open the stream

**Comment by apo86** [comment]
Did you set BOTH required login tokens?
See https://github.com/anxdpanic/plugin.video.twitch/wiki/Private-API-Credentials---OAuth-Token#2-enabling-additional-features for details.

**Comment by ffais** [comment]
That was the problem I didn't set the second token.
With both tokens everything works fine.

Thank you for the support.
