### ISSUE TITLE
Can't request a new OAuth Token (web page redirect to old API)

### ISSUE THREAD

**Issue by sedric** [MrSprigster/Twitch.tv-on-XBMC#676]
### Context

* Add-on Version: 3.0.0
* Kodi Version: 20.0
* Kodi GUI Language: Fr
* Operating System: LibreElec 11.0
* Operating System Language: En

------

### Expected Behavior

Going to https://twitchaddon.page.link/Z1iP should give me an OAuth token

------

### Current Behavior

I only get a page that say "Gone" (with an HTTP 410 error), I am redirected to a page on the old API : https://api.twitch.tv/kraken/oauth2/authorize 

Tested with Firefox ESR, Chromium and wget.

**Comment by sedric** [comment]
Just in case the URL had changed : this is the one that the extension display on Kodi

**Comment by steph09** [comment]
Experiencing the same problem.

**Comment by Underpath** [comment]
Had the same issue. Seems the URL did change indeed, I was able to get the token by using this link: https://id.twitch.tv/oauth2/authorize?response_type=token&client_id=ps2ed9zlj8zyqztsdz2tl4uys84b8k&redirect_uri=https://anxdpanic.github.io/plugin.video.twitch/token/&scope=user:read:follows+user:edit:follows+user:read:subscriptions+chat:read+chat:edit&force_verify=false&state

**Comment by TheDiggler** [comment]
Same issue but the link from Underpath worked perfectly!  Thanks!

**Comment by disc-kuraudo** [comment]
And I thought it's an April Fools' joke.

**Comment by anxdpanic** [comment]
**https://twitchaddon.page.link/1Sk5** issue fixed and submitted to official repository
