### ISSUE TITLE
Playing a stream immediately fails with error

### ISSUE THREAD

**Issue by akb825** [MrSprigster/Twitch.tv-on-XBMC#682]
### Context

Starting today streams fail to play immediately

* Add-on Version: 3.0.1
* Kodi Version: 20.1
* Kodi GUI Language: English
* Operating System: Arch Linux
* Operating System Language: English

------

### Expected Behavior

Stream plays after selecting it.

------

### Current Behavior

Stream fails immediately with an error banner directing the user to view the log for more details.

------

### Steps to Reproduce

1. Open the Twitch plugin in Kodi.
2. Browse to a stream.
3. Attempt to play the stream.

------

### Log

[kodi.log](https://github.com/anxdpanic/plugin.video.twitch/files/11619625/kodi.log)

------

### Additional Information

Clearing the function cache has no effect.

------

**Comment by Cnuut** [comment]
https://github.com/streamlink/streamlink/issues/5370

**Comment by apo86** [comment]
It still works for me, probably not rolled out everywhere yet. But from what I read this is basically the same problem as https://github.com/anxdpanic/plugin.video.twitch/issues/667 now expanded to stream playback.

Not to be a downer, but unless Twitch reverts this change, it's probably a RIP. Even if the streamlink guys come up with something it's gonna be a constant game of cat and mouse, plus Twitch might even get more hostile for breaking their anti-bot-measures.

Looks like killing 3rd party apps is in style right now :-/

**Comment by Cnuut** [comment]
Yeah the Twitchapp on Kodi still works for me, streamlink does not, strange. **UPDATE1**: (works now with the SwitchID) **UPDATE2**: aaand right now it works as it did before all strangeness....

**Comment by alterNERDtive** [comment]
Using the `Client-ID` of the Switch app seems to be a workaround for now: https://github.com/streamlink/streamlink/issues/5370#issuecomment-1572576728

Any way to set that in this addon?

**Comment by apo86** [comment]
@alterNERDtive 
Settings -> Subscriber and Turbo Benefits -> OAuth Client ID
Settings -> Developer -> OAuth Client ID

It may be enough to change one of the two, but not sure.

**Comment by alterNERDtive** [comment]
Tried the latter, didn’t work and reset to empty. I’ll try both I guess.

**Comment by fearlesschicken** [comment]
It seems whatever twitch changed that broke this has been reverted and the plugin is working again.  Same with streamlink and other twitch streaming tools.

**Comment by akb825** [comment]
It's working for me now, I guess we'll see if this was a temporary hiccup or if it's simply an early stage of a rollout for the next stage of the recent 3rd party appocolypse...

**Comment by akb825** [comment]
It's been a few days now without issues, I'll go ahead and close this issue.
