### ISSUE TITLE
GONE [410] this api is not available error

### ISSUE THREAD

**Issue by nightemt** [MrSprigster/Twitch.tv-on-XBMC#684]
Just started getting this error a few days ago. I reauthorized my token twice and uninstalled and reinstalled. I’m running the current version from the repo and my kodi is up to date. Is anyone else having this issue? Please help.

**Comment by Thrius** [comment]
@nightemt Yes, I have this same issue when trying to select Following/Channels. This issue doesn't seem to occur when I select Live Channels. Interestingly enough I can search for a channel I follow and then play the VOD. So it seems the followed channels API endpoint is maybe broken or changed.

**Comment by apo86** [comment]
Still works for me. Do you use both kinds of oauth tokens? (https://github.com/anxdpanic/plugin.video.twitch/wiki/Private-API-Credentials---OAuth-Token)

**Comment by Thrius** [comment]
@apo86 Yes and thanks for the link. I went through and generated a new "oauth_token_helix" and "private_oauth_token". I did notice that the link: [twitchaddon.page.link/Z1iP](http://twitchaddon.page.link/Z1iP) hasn't worked for a long time so I've been using: [twitchaddon.page.link/1Sk5](http://twitchaddon.page.link/1Sk5). What link are you using that seems to work?

**Comment by apo86** [comment]
Yes, 1Sk5 is the right one. The addon hasn't been updated yet, but the wiki already has this link.

Also I now get what you're saying. I was confused because I always use "Following LIVE Channels", which is still working. But you're talking about "Following Channels", which is indeed broken.
I have a fix and will open a PR tomorrow (today I guess, turns out it's 5 AM), but I'm not sure if anxdpanic is around to push it to the official repository. So you might have to patch it manually.

**Comment by adanrg** [comment]
I've also ran into this problem randomly in the last few days. I've managed to trace it back to a Twitch API call, which is being deprecated. This is the original announcement from Twitch:
https://discuss.dev.twitch.tv/t/follows-endpoints-and-eventsub-subscription-type-are-now-available-in-open-beta/43322

The API call currently used by this addon is:
https://dev.twitch.tv/docs/api/reference/#get-users-follows
The successor seems to be this API call:
https://dev.twitch.tv/docs/api/reference/#get-followed-channels

They are doing partial shutdowns starting from 6th of September. On 12th of September, this API will cease to exists forever. The timeline is here:
https://discuss.dev.twitch.tv/t/legacy-follows-api-and-eventsub-shutdown-timeline-updated/46769/1

**Comment by adanrg** [comment]
It seems, while I was writing my previous comment, others also figured it out. Nice!

**Comment by nightemt** [comment]
Sorry I’m new to this. So is this something that we need to wait for the repo to update to regain the functionality?

**Comment by apo86** [comment]
@nightemt Yes, new version needs to be merged into the official Kodi repository. Shouldn't take too long hopefully :)

**Comment by nightemt** [comment]
> @nightemt Yes, new version needs to be merged into the official Kodi repository. Shouldn't take too long hopefully :)

Thanks.

**Comment by nightemt** [comment]
Looks like it broke again.

**Comment by apo86** [comment]
The new version isn't available yet. It has been submitted to the official repository, now it needs to be merged by a member of team Kodi.

**Comment by nightemt** [comment]
> The new version isn't available yet. It has been submitted to the official repository, now it needs to be merged by a member of team Kodi.

Ok. Hope that fixes it again. The fix they pushed last week worked for a short time.

**Comment by apo86** [comment]
That had nothing to do with us actually. Twitch re-enabled the old API briefly, before disabling it permanently on the 12th.
Anyways, the new addon version should be available now.
